#!/usr/bin/env python3

"""This is the main file"""

from core import Core


def main():
    try:
        core = Core()
        core.start()
    except KeyboardInterrupt:
        return 0


if __name__ == "__main__":
    main()
