#!/usr/bin/env python3.7

"""This is the main file"""

from core import Core


def main():
    try:
        core = Core()
        core.start()
    except KeyboardInterrupt:
        print("Shutting down...")


if __name__ == '__main__':
    main()
